### ISSUE TITLE
About weird communication issue when following the instruction with UART mode

### ISSUE THREAD

**Issue by YunchuZhang** [psyonicinc/ability-hand-api#2]
Hi there,
I am trying to run the python examples. I follow the readme to connect the wires as described.
The live_plot_demo.py script does run, but it does not hear anythings back and keep resetting.
![Screenshot 2023-02-17 21:02:12](https://user-images.githubusercontent.com/33641269/219839657-35a20204-d7f2-4f16-ab20-a39878da18b4.png)

Thus, I try to use minicom to send We16 to change the mode. As the readme described here:

Before running, please ensure the hand is in UART communication mode - this can be configured over Bluetooth with the binary setting command We16
![Screenshot 2023-02-17 21:02:32](https://user-images.githubusercontent.com/33641269/219839686-a5dee969-675e-42ee-8984-96250962f4c1.png)

However, it still does not help at all. Any clues for how to solve it?

**Comment by YunchuZhang** [comment]
Hi, I tried with 460800 as well. It doesn’t work.
Does my way to send the We16 command work? Is there any response from the
command to show it receives it?

**Comment by Ocanath** [comment]
The hand will respond with a notification 'success'. You can verify the bit setting with RZ16, it will respond with '0' if the bit is set. You can use the Ability Hand app as a Bluetooth client, go to the settings icon and 'developer mode'

**Comment by YunchuZhang** [comment]
Hi, the second way"You can use the Ability Hand app as a Bluetooth client, go to the settings icon and 'developer mode'" works!
But it is still weird that sending "We16" directly with serialtool(minicom) does not work.

**Comment by Ocanath** [comment]
By design and per the documentation, flash settings are modifiable only using the bluetooth low energy interface (GATT). It is not possible to use UART via a serial client such as minicom to change these settings. Glad you were able to get it working!
